root: true

parser: '@typescript-eslint/parser'

settings:
  import/parsers:
    '@typescript-eslint/parser': ['.ts']

env:
  browser: true
  node: true
  mocha: true
  es2020: true

globals:
  NodeJS: true
  KOISHI_CONFIG: true

extends:
  - standard

plugins:
  - mocha
  - '@typescript-eslint'

rules:
  comma-dangle:
    - error
    - always-multiline

  dot-notation: off

  generator-star-spacing:
    - error
    - after

  max-len:
    - warn
    - 160

  no-mixed-operators: off
  no-use-before-define: off
  no-return-assign: off
  no-sequences: off
  one-var: off
  operator-linebreak: off

  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true

  yield-star-spacing:
    - error
    - after

  # node
  # node/no-callback-literal: off

  # typescript
  import/export: off

  default-param-last: off
  '@typescript-eslint/default-param-last': error

  func-call-spacing: off
  '@typescript-eslint/func-call-spacing': error

  keyword-spacing: off
  '@typescript-eslint/keyword-spacing': error

  # no-useless-escape: offhttps://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-redeclare.md
  no-redeclare: off

  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none

  no-dupe-class-members: off
  '@typescript-eslint/no-dupe-class-members': error

  # https://github.com/typescript-eslint/typescript-eslint/issues/239
  no-inner-declarations: off

  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor': warn

  semi: off
  '@typescript-eslint/semi':
    - error
    - never
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none

  space-before-function-paren: off
  '@typescript-eslint/space-before-function-paren':
    - error
    - anonymous: always
      asyncArrow: always
      named: never
  '@typescript-eslint/type-annotation-spacing': error
