name: Test

on:
  push:
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Create .npmrc
        run: 'echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc'
      - name: Install
        run: yarn
      - name: Build
        run: yarn build:ci
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test:json
      - name: Report Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          name: codecov
      - name: Publish
        run: npx ts-node build/publish
